import './globals.css';
import { Geist, Geist_Mono } from 'next/font/google';
import ClerkWrapper from '@/src/components/ClerkWrapper';
import Provider from '../components/Provider';

const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
  display: 'swap', // ensures SSR and client are consistent
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
  display: 'swap',
});

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Wrap dynamic fonts in a client-safe div */}
        <div className={`${geistSans.variable} ${geistMono.variable}`}>
          <Provider>
            <ClerkWrapper>{children}</ClerkWrapper>
          </Provider>
        </div>
      </body>
    </html>
  );
}
