import './globals.css'
import { Geist, Geist_Mono } from 'next/font/google'
import ClerkWrapper from '@/src/components/ClerkWrapper'
import Provider from '../components/Provider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <Provider>
        <ClerkWrapper>
          {children}
        </ClerkWrapper>
      </Provider>
    </body>
  </html>
  )
}
